### ISSUE TITLE
Refactor GET `/types/{name}` endpoint

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-services#157]
The `/types/{name}` endpoint currently returns an empty response. Investigate the cause and fix the DAOs if necessary.

The `getTypeByName` method is used to fetch the required document. We need to make sure that the query used is based on fetching documents on the basis of names (`dc:title` key in the document).

Since it is possible that a user may want to see all the versions in existence, we can return the list of the documents fetched only if no version parameter is specified. Otherwise, if the parameter is specified, then filter the results for that version number and return that.  Something similar to:
https://github.com/IN-CORE/incore-services/blob/c1255109945ac07b725fcc1c1fdd30e4d06704bb/server/hazard-service/src/main/java/edu/illinois/ncsa/incore/service/hazard/controllers/EarthquakeController.java#L298

Sort, OrderBy, Skip & Limit:
- Defaults are:
    - *Sort:* descending (latest first, followed by numbers in decreasing order)
    - *OrderBy:* version number
    - *Offset:* 0
    - *Limit:* 20

Permissions:
- Any user can read the data.

The response from this function can look like this. (feel free to modify if there is a better idea)
```
[
    DocumentObject1,
    DocumentObject2,
    DocumentObject3,
    .
    .
    .
]
```
OR

```
[
    DocumentObject
]
```

Also, add the capability to send this list in an HTML format if the user adds `.html` in the end else, default to JSON. 

Meaning, if the user enters, `https://incore.ncsa.illinois.edu/semantics/api/types/TypeName1` or `https://incore.ncsa.illinois.edu/semantics/api/types/TypeName1.json` the response should be JSON OR if the user enters `https://incore.ncsa.illinois.edu/semantics/api/types/TypeName1.html` return an HTML page listing the response.

**Comment by ylyangtw** [comment]
after team discussion, dc:title should be unique, so we dont need to implement sorting
