### ISSUE TITLE
Refactor GET `/types/search`

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-services#158]
Revisit the search implementation to make sure that the API endpoint returns correct responses by searching the given search string in the title field of the document.
https://github.com/IN-CORE/incore-services/blob/c1255109945ac07b725fcc1c1fdd30e4d06704bb/server/semantics-service/src/main/java/edu/illinois/ncsa/incore/service/semantics/controllers/TypeController.java#L135

Permissions:
- Any user can read the data.

**Comment by ylyangtw** [comment]
Since this endpoint doesn't require any changes, I will close this issue.
