### ISSUE TITLE
Refactor POST `/types` API

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-services#159]
Currently any user in the system can post to this endpoint. Our goal is to only allow users, who have `incore_admin` or `incore_ncsa` in their groups to POST data for now.

Check `authorizer.isUserAdmin` and `authorizer.canWrite` methods for appropriate access control.

Read how access control is performed in this endpoint to get an idea of how to perform access control here.
https://github.com/IN-CORE/incore-services/blob/c1255109945ac07b725fcc1c1fdd30e4d06704bb/server/hazard-service/src/main/java/edu/illinois/ncsa/incore/service/hazard/controllers/EarthquakeController.java#L152

**Comment by ylyangtw** [comment]
@Rashmil-1999 
After testing and looking at the codes, non-admin groups cannot post anything and would only get a message "xxx is not an admin."
Do we still want to keep all semantics endpoints for admin groups?
```
    @Inject
    public TypeController(
        @Parameter(name = "User credentials.", required = true) @HeaderParam("x-auth-userinfo") String userInfo,
        @Parameter(name = "User groups.", required = false) @HeaderParam("x-auth-usergroup") String userGroups
    ) {
        this.username = UserInfoUtils.getUsername(userInfo);
        this.groups = UserGroupUtils.getUserGroups(userGroups);
        // we want to limit the semantics service to admins for now
        this.authorizer = new Authorizer();
        if (!this.authorizer.isUserAdmin(this.groups)) {
            throw new IncoreHTTPException(Response.Status.FORBIDDEN, this.username + " is not an admin.");
        }
    }
```

**Comment by ylyangtw** [comment]
Just checked other issues. Some endpoints are open to users.
