### ISSUE TITLE
Refactor DELETE `/types/{id}` endpoint

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-services#160]
Change the endpoint to `/types/{name}` and use the name (`dc:title`) to find the file and delete it instead of the `_id` field.

This endpoint will be Admin only. So set up access control in this fashion.
https://github.com/IN-CORE/incore-services/blob/c1255109945ac07b725fcc1c1fdd30e4d06704bb/server/hazard-service/src/main/java/edu/illinois/ncsa/incore/service/hazard/controllers/EarthquakeController.java#L152

I am still unsure whether we should use `dc:title` to fetch and delete since, `_id` would me a unique identifier and there may be 1+ documents having same `dc:title` field.

**Comment by ylyangtw** [comment]
I think `_id` is better since the `Type` collection can have multiple ids for the same name. 
![image](https://github.com/IN-CORE/incore-services/assets/63822845/b731fac8-d040-4a15-b6e2-549661f58371)

**Comment by ylyangtw** [comment]
After team discussion, we should add unique constraints to 'dc:title'
