### ISSUE TITLE
Test vector tile in geoserver

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-services#271]
Test vector tile option in geoserver using SLC buildings to see if it enhances the performance.

**Comment by longshuicy** [comment]
> VectorTile is not performing as we expected. (note that there is another test we need to do .. it requires more time and efforts -> this is not feasible for this time).
> Therefore, we will go with Openlayers with WMS layer.
> In order to display the property (attribute) of the building, we can use "WMS GetFeatureInfo" which supported by OpenLayers. Here is an example: https://openlayers.org/en/latest/examples/getfeatureinfo-layers.html
> another example: https://openlayers.org/en/latest/examples/getfeatureinfo-tile.html
