### ISSUE TITLE
Add endpoint to project-service to finalize a workflow

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-services#335]
We need a way to mark the workflow in a project to be finalized without having the need to post the entire project document with just 1 field change. This endpoint could look like: /projects/{projectId}/workflows/{workflowId}/finalize which would make the workflow with that it in that project finalized.

**Comment by ywkim312** [comment]
@Rashmil-1999 I have a question. So it means that there is an item or entry in the workflow, such as finalize: true or false. and this endpoint with make the to be true? Or can you add little more detail?
