### ISSUE TITLE
Sync user's groups from LDAP/JWT token to database - for User Allocation management

### ISSUE THREAD

**Issue by ghost** [IN-CORE/incore-services#74]
We should be able to populate user groups in `UserGroups` collection in real-time for the Mongo View to function as expected. This is needed for user allocation functionality.

Some ideas:
- Parse JWT token, compare it to the user's group in cache (see LdapClient.java), store in the collection if different
- We update user groups in cache from LDAP every 15 mins(env variable), at this point also update the database collection

**Comment by ywkim312** [comment]
This has been implemented
