### ISSUE TITLE
Update creator information

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-services#97]
There are several datasets that don't have creator information. Find the creator and update them.

```
hazarddb EarthquakeDataset 5dfa3e36b9219c934b64c231
hazarddb EarthquakeDataset 5dfa4058b9219c934b64d495
hazarddb EarthquakeDataset 5dfa41aab9219c934b64d4b2
hazarddb EarthquakeDataset 5dfa4300b9219c934b64d4d0
hazarddb EarthquakeDataset 5dfa4417b9219c934b64d4d3
hazarddb EarthquakeDataset 5dfa5115b9219c934b68e6bf
hazarddb EarthquakeDataset 5dfa51bfb9219c934b68e6c2
hazarddb EarthquakeDataset 5dfbca0cb9219c101fd8a58d
hazarddb EarthquakeModel 5dfa8415b9219c101fc9244b
hazarddb TsunamiDataset 5df90137b9219cd00cb774ec
hazarddb TsunamiDataset 5df90761b9219cd00ccff258
hazarddb TsunamiDataset 5df90871b9219cd00ccff273
hazarddb TsunamiDataset 5df90e07b9219cd00ce971e7
hazarddb TsunamiDataset 5df910abb9219cd00cf5f0a5
```

**Comment by ywkim312** [comment]
hazarddb EarthquakeDataset 5dfa4058b9219c934b64d495: cnavarro
hazarddb EarthquakeDataset 5dfa41aab9219c934b64d4b2: cnavarro
hazarddb EarthquakeDataset 5dfa4300b9219c934b64d4d0: cnavarro
hazarddb EarthquakeDataset 5dfa4417b9219c934b64d4d3: cnavarro
hazarddb EarthquakeDataset 5dfa5115b9219c934b68e6bf: cnavarro
hazarddb EarthquakeDataset 5dfa51bfb9219c934b68e6c2: cnavarro
hazarddb EarthquakeDataset 5dfbca0cb9219c101fd8a58d: cnavarro
hazarddb EarthquakeModel 5dfa8415b9219c101fc9244b: vnarah2
hazarddb TsunamiDataset 5df90137b9219cd00cb774ec: cnavarro
hazarddb TsunamiDataset 5df90761b9219cd00ccff258: cnavarro
hazarddb TsunamiDataset 5df90871b9219cd00ccff273: no name, space entry 8
hazarddb TsunamiDataset 5df90e07b9219cd00ce971e7: no name, space entry 8
hazarddb TsunamiDataset 5df910abb9219cd00cf5f0a5: cnavarro

**Comment by ywkim312** [comment]
@navarroc Chris, there are two datasets that have no name even in the space. Could you check my above comment and check those two datasets without the name and let me know what you think for the creator?

**Comment by navarroc** [comment]
Since they are in the incore space, maybe make "incore" the creator?

**Comment by ywkim312** [comment]
Updated all and used 'incore; for the no named one as you guided.

**Comment by ywkim312** [comment]
@navarroc If you're okay, let's close this issue. All the data has been updated

**Comment by longshuicy** [comment]
can i close?

**Comment by ywkim312** [comment]
I think this is done. Closing it.
