### ISSUE TITLE
Create endpoints for searching space, and give space name and get space id back

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-services#98]

**Comment by ywkim312** [comment]
![image](https://user-images.githubusercontent.com/12547573/211095348-65592c10-9a8b-4781-80b4-7a5ec5d2dfcb.png)

**Comment by longshuicy** [comment]
I think we are fine without this endpoint since now you can filter space by name? (your other PR)
Thoughts?

**Comment by ywkim312** [comment]
I just created the space by name and space by id was already there so basically this is done. Closing it.
